services:
  - type: web
    name: bakery-erp-backend
    env: node
    plan: free
    baseDir: server
    buildCommand: npm install && npm rebuild sqlite3 --build-from-source
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: npm_config_build_from_source
        value: "true"
      - key: npm_config_python
        value: "python3"
